//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Input/SpawnerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SpawnerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SpawnerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SpawnerInputActions"",
    ""maps"": [
        {
            ""name"": ""Spawner"",
            ""id"": ""2214be2e-3311-49cb-90d0-621db0fb6873"",
            ""actions"": [
                {
                    ""name"": ""Spawn"",
                    ""type"": ""Button"",
                    ""id"": ""74142d7a-5605-44f0-9f91-b6d51c4ee75f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2d8ad06e-f0a5-4864-a03d-64c851dcf682"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Spawner
        m_Spawner = asset.FindActionMap("Spawner", throwIfNotFound: true);
        m_Spawner_Spawn = m_Spawner.FindAction("Spawn", throwIfNotFound: true);
    }

    ~@SpawnerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Spawner.enabled, "This will cause a leak and performance issues, SpawnerInputActions.Spawner.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Spawner
    private readonly InputActionMap m_Spawner;
    private List<ISpawnerActions> m_SpawnerActionsCallbackInterfaces = new List<ISpawnerActions>();
    private readonly InputAction m_Spawner_Spawn;
    public struct SpawnerActions
    {
        private @SpawnerInputActions m_Wrapper;
        public SpawnerActions(@SpawnerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Spawn => m_Wrapper.m_Spawner_Spawn;
        public InputActionMap Get() { return m_Wrapper.m_Spawner; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpawnerActions set) { return set.Get(); }
        public void AddCallbacks(ISpawnerActions instance)
        {
            if (instance == null || m_Wrapper.m_SpawnerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpawnerActionsCallbackInterfaces.Add(instance);
            @Spawn.started += instance.OnSpawn;
            @Spawn.performed += instance.OnSpawn;
            @Spawn.canceled += instance.OnSpawn;
        }

        private void UnregisterCallbacks(ISpawnerActions instance)
        {
            @Spawn.started -= instance.OnSpawn;
            @Spawn.performed -= instance.OnSpawn;
            @Spawn.canceled -= instance.OnSpawn;
        }

        public void RemoveCallbacks(ISpawnerActions instance)
        {
            if (m_Wrapper.m_SpawnerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpawnerActions instance)
        {
            foreach (var item in m_Wrapper.m_SpawnerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpawnerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpawnerActions @Spawner => new SpawnerActions(this);
    public interface ISpawnerActions
    {
        void OnSpawn(InputAction.CallbackContext context);
    }
}
